# Generated by Django 4.0.6 on 2024-08-13 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 8, 14, 46, 859240), verbose_name='Date'),
        ),
    ]
