# Generated by Django 5.1 on 2024-08-16 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 16, 10, 45, 5, 961275), verbose_name='Date'),
        ),
    ]
