# Generated by Django 5.1 on 2024-08-16 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='ftitle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 16, 11, 1, 51, 557779, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
